### ISSUE TITLE
Use -AgentGuid with Set-ePOwerShellTag or Remove-ePOComputer

### ISSUE THREAD

**Issue by UolSimon** [UNT-CAS/ePOwerShell#24]
ePowershell has been really useful for remote administration and I have written a script to remove old duplicate devices in our EPO. 

The problem is that because we can only use the ComputerName child item when using Set-ePOwerShellTag or Remove-ePOComputer we cant specify which of these duplicate devices we want to set a tag on / remove from EPO.

Please can Set-ePOwerShellTag or Remove-ePOComputer be configured to also accept AgentGUID?

Many thanks!

**Comment by UolSimon** [comment]
I've done a bit of digging. The only way of setting a tag is to use the name, however you can use the parent ID when using system.delete (which I presume is what Remove-ePoComputer is using). 

In the end we have been able to remove machines by invoking this command:

(epo path)/remote/system.delete?ids=$variable

Hopefully this helps someone!

**Comment by marranaga** [comment]
I looked at our ePO instance (5.9) to check what parameters it'll allow. Looks like it accepts the ParentID when specifying computers, which should be unique per system. The `Set-ePOTag` and `Remove-ePOTag` functions will be updated to go off of this ID rather than name. `Remove-ePOComputer` is already going off of the ParentID while deleting computers, so adding another parameter for AgentGuid will be pretty easy.

Available parameters from ePO for `Set-ePOTag` and `Remove-ePOTag`:
![image](https://user-images.githubusercontent.com/9207580/62978895-fd85a500-bde7-11e9-8e4e-540a833044b5.png)

**Comment by UolSimon** [comment]
Sounds great! Thanks!

**Comment by marranaga** [comment]
As of version 2.2.2, we now use computer parent ID and tag ID to set/remove tags, and several functions have been updated to accept an Agent Guid!
